apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nodejs
  labels:
    app: dummy-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-nodejs
  template:
    metadata:
      labels:
        app: dummy-nodejs
    spec:
      containers:
        - name: dummy-nodejs
          image: 230600/dummy-nodejs:v2
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production" 
